---

- name: Install the package nginx
  ansible.builtin.apt:
    name: nginx

- name: Disable NGINX Default Virtual Host
  become: true
  command: unlink /etc/nginx/sites-enabled/default
  ignore_errors: true

- name: create k3s config file
  become: true
  file:
    path: /etc/nginx/sites-available/k3s_proxy.conf
    state: touch

- name: Amend NGINX Conf File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/k3s_proxy.conf
      marker: ""
      block: |
        server {
            listen 80;
            location /whoami {
                proxy_pass http://192.168.121.207:80;
                proxy_set_header Authorization "";
                proxy_read_timeout 90s;
            }
        }
- name: Link NGINX Kibana Reverse Proxy
  become: yes
  command: ln -s /etc/nginx/sites-available/k3s_proxy.conf /etc/nginx/sites-enabled/k3s_proxy.conf
  ignore_errors: true

- name: Make Sure NGINX Service Is Running
  become: true
  service:
    name: nginx
    state: restarted
    enabled: true
