---

# ubuntu see https://computingpost.medium.com/install-and-configure-dnsmasq-on-ubuntu-22-04-20-04-18-04-1919a438e80d

- name: ansible_pkg_mgr info
  debug:
    var: ansible_pkg_mgr

- name: Install dnsmasq on ubuntu
  apt:
    name: dnsmasq
    state: present
  become: true

- name: Override Service
  become: true
  template:
    src: override.conf
    dest: /etc/systemd/system/dnsmasq.service.d/override.conf
    mode: 0644

- name: Set configuration file
  become: true
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
    mode: 0644
  notify:
    - disable systemd-resolved
    - unlink resolv.conf
    - generate resolv.conf
    - restart dnsmasq
    # - restart docker
    # - disable firewalld
