---

- hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars/all.yml
  tasks:

    - name: delete a k8s namespace
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: absent
