---

- hosts: localhost
  connection: local

  vars:
    gitlab_username: "'{{ lookup('ansible.builtin.env', 'GITLAB_USERNAME') }}'"
    gitlab_email: "'{{ lookup('ansible.builtin.env', 'GITLAB_EMAIL') }}'"
    gitlab_token: "'{{ lookup('ansible.builtin.env', 'GITLAB_TOKEN') }}'"

  tasks:

    - name: hostname
      command: hostname
      register: out

    - name: debug out
      debug:
        var: out

    - name: debug
      debug:
        msg:
          - "GITLAB_USERNAME: {{ gitlab_username }}"
          - "KUBECONFIG: {{ kubeconfig }}"
          - "GITLAB_EMAIL: {{ gitlab_email }}"
          - "GITLAB_SECRET: {{ gitlab_token }}"
          - "Namespace: {{ namespace }}"

    # - name: delete a k8s namespace
    #   kubernetes.core.k8s:
    #     name: "{{ namespace }}"
    #     api_version: v1
    #     kind: Namespace
    #     state: absent
    #     kubeconfig: "{{ kubeconfig }}"

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ kubeconfig }}"

    - name: create gitlab-secret
      kubernetes.core.k8s:
        state: present
        name: "{{ namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/dockerconfigjson
          metadata:
            name: credgitlab
            namespace: "{{ namespace }}"
          data:
            .dockerconfigjson: "{{ lookup('template', 'templates/gitlab_config_data.json' ) | tojson | b64encode }}"

# --- EOF
