---

- hosts: localhost
  connection: local

  tasks:

    - name: debug
      debug:
        msg:
          - "KUBECONFIG: {{ kubeconfig }}"
          - "Namespace: {{ namespace }}"
          - "GITLAB_USERNAME: {{ gitlab_username }}"
          - "GITLAB_EMAIL: {{ gitlab_email }}"
          - "GITLAB_TOKEN: {{ gitlab_token }}"
          - "GITLAB_AUTH: {{ gitlab_auth }}"
          - "Auth: {{ lookup('template', 'templates/gitlab_config_data.json' ) | tojson | b64encode }}"

    - name: create gitlab-secret
      kubernetes.core.k8s:
        state: present
        name: "{{ namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/dockerconfigjson
          metadata:
            name: gitlab-auth
            namespace: "{{ namespace }}"
          data:
            .dockerconfigjson: "{{ lookup('template', 'templates/gitlab_config_data.json' ) | tojson | b64encode }}"

    - name: create config-map
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        template: templates/config_map.j2.yml
        kubeconfig: "{{ kubeconfig }}"

    - name: create deployment
      kubernetes.core.k8s:
        state: present
        namespace: '{{ namespace }}'
        template:
          path: 'templates/deploy_goapp.j2.yml'
        kubeconfig: '{{ kubeconfig }}'

    # - name: create service
    #   kubernetes.core.k8s:
    #     state: present
    #     namespace: "{{ namespace }}"
    #     template: templates/service.j2.yml
    #     kubeconfig: "{{ kubeconfig }}"

    # - name: create ingress
    #   kubernetes.core.k8s:
    #     state: present
    #     namespace: "{{ namespace }}"
    #     template: templates/deploy_ingress.j2.yml
    #     kubeconfig: "{{ kubeconfig }}"

# --- EOF
