---

- name: deploy from gitlab
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: pfistera
        api_version: v1
        kind: Namespace
        state: present

    - name: create images repo secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: regcred
            namespace: pfistera
          data:
            config_data.json: "{{ lookup('template', 'image_secret.json.j2' ) | tojson | b64encode }}"

    - name: deploy
      kubernetes.core.k8s:
        state: present
        namespace: pfistera
        template:
          path: 'deploy_whoami.j2.yml'

    - name: Get a list of all Services in the myapp namespace.
      kubernetes.core.k8s_info:
        kind: Service
        namespace: pfistera
      register: out

    - name: Display number of Services in the myapp namespace.
      debug:
        var: out.resources
