---

- name: lets install k3s
  hosts: master,worker
  connection: ssh
  gather_facts: true
  remote_user: vagrant

  tasks:

  - name: install yq
    become: true
    copy:
      src: yq
      dest: /usr/local/bin/yq
      owner: root
      group: root
      mode: '0755'

  - name: check yq
    become: true
    shell: /usr/local/bin/yq -V

  - name: install helm
    become: true
    copy:
      src: helm
      dest: /usr/local/bin/helm
      owner: root
      group: root
      mode: '0755'

  - name: check helm
    shell: /usr/local/bin/helm version

  - name: install kubectl
    become: true
    copy:
      src: kubectl
      dest: /usr/local/bin/kubectl
      owner: root
      group: root
      mode: '0755'

  - name: check kubectl
    shell: /usr/local/bin/kubectl version --client

  - name: install k3s
    become: true
    copy:
      src: k0s
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: '0755'

  - name: check k3s
    shell: /usr/local/bin/k3s --version