---

- name: lets install k0s
  hosts: k0sworker
  connection: ssh
  gather_facts: true
  remote_user: vagrant

  tasks:

  - name: reset k0s
    become: True
    shell: |
      /usr/local/bin/k0s stop
      /usr/local/bin/k0s reset
      rm -rf /etc/k0s
      rm -rf /var/lib/k0s

  - name: create k0s folders
    become: True
    shell: |
      mkdir /var/lib/k0s/ || true
      mkdir /etc/k0s/ || true

  - name: copy /etc/k0s/token-file
    become: True
    copy:
      src: tmp/token-file
      dest: /etc/k0s/token-file

  - name: start k0s
    become: True
    shell: |
      /usr/local/bin/k0s install worker --token-file /etc/k0s/token-file
      /usr/local/bin/k0s start
      sleep 60
      /usr/local/bin/k0s status