---

#
# first register in gitea a oauth2 app with http://woodpecker.localnet/authorize
# and get clientid and secret
#

- name: deploy woodpecker
  hosts: localhost
  gather_facts: false
  connection: false

  tasks:
# --- EOF
