---
- name: lets manage minikube on host somsi
  hosts: all
  connection: ssh
  gather_facts: false

  tasks:

  - name: stop all
    shell:
      cmd: |
            docker ps
            docker ps | grep -v CONTAINER | awk '{print $1}' | xargs -i{} docker stop {}
            minikube stop
            minikube delete
            rm -rf ~/.minikube
    register: status
    tags:
      - stop_all
      - start
  - debug:
      msg:
        - "xx {{ status.stdout_lines }}"
        - "yy {{ status.stderr_lines }}"
    tags:
      - stop_all
      - start

  - name: start minikube
    shell: 
      cmd:  |
            minikube start
            minikube status
    register: status
    tags:
    - start
  - debug:
      msg:
        - "{{ status.stdout_lines }}"
        - "{{ status.stderr_lines }}"
    tags:
    - start

  - name: minikube status
    shell: 
      cmd:  |
            minikube status
    register: msg
    tags:
    - status
  - debug: msg="{{ msg.stdout }}"
  - debug: msg="{{ msg.stderr }}"
  # - debug:
  #     msg:
  #       - "xxx {{ status.msg.stdout }}"
  #       - "yyy {{ status.stderr_lines }}"
  #   tags:
  #   - status
