---
# https://kifarunix.com/install-nexus-repository-manager-on-ubuntu/

- name: lets manage minikube on host somsi
  hosts: somsi
  connection: ssh
  gather_facts: True
  become: True

  tasks:


    - name: openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: present

    - name: add nexus user
      ansible.builtin.user:
        name: nexus
        comment: nexus-user
        group: adm
        home: /opt/nexus
        shell: /bin/bash

    - name: download oss nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.38.1-01-unix.tar.gz
        dest: /var/tmp/nexus.tar.gz

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /opt/nexus
        state: directory
        mode: "0755"
        owner: nexus

    - name: unpack nexus
      shell: |
        set -aeEux
        tar xzf /var/tmp/nexus.tar.gz -C /opt/nexus --strip-components=1
        chown -R nexus /opt/nexus

    - name: template /opt/nexus/bin/nexus.vmoptions
      ansible.builtin.template:
        src: nexus.vmoptions.j2
        dest: /opt/nexus/bin/nexus.vmoptions
        owner: nexus
        group: adm
        mode: "0644"


    - name: template /opt/nexus/bin/nexus.vmoptions
      ansible.builtin.template:
        src: nexus.systemd.j2
        dest: /etc/systemd/system/nexus.service
        owner: root
        group: root
        mode: "0644"

    - name: startup nexus
      shell: |
        set -aeEux
        /opt/nexus/bin/nexus stop
        systemctl daemon-reload
        systemctl enable --now nexus.service
        systemctl status nexus