---
- name: This is a hello-world example
  hosts: all
  connection: ssh
  gather_facts: False

  tasks:

  - name: docker stop all
    ansible.builtin.shell: 
      cmd: |
        docker ps
        docker stop gitea
        docker stop drone
        docker stop drone-runner-docker
        docker stop traefik
        docker ps
    register: status
  - debug:
      msg: "docker status {{ status.stdout }}"
  
  - name: delete existing cluster
    ansible.builtin.shell: 
      cmd:  /home/pfistera/bin/kind delete cluster
    register: status
    tags:
      - kind_stop
  - debug:
      msg: "kind delete status {{ status.stdout }}"
    tags:
      - kind_stop

  - name: start kind
    ansible.builtin.shell: 
      cmd:  /home/pfistera/bin/kind create cluster --config=./deploy/kind/cluster.yml --image kindest/node:v1.19.1
      chdir: /home/pfistera/workspace/cf-for-k8s
    register: status
  - debug:
      msg: "kind start status {{ status.stdout }}"

  - name: start kind
    ansible.builtin.shell: 
      cmd:  /home/pfistera/bin/kapp deploy -y -a cf -f <(/home/pfistera/bin/ytt -f config -f ./tmp/cf-values.yml)
      chdir: /home/pfistera/workspace/cf-for-k8s
      executable: /bin/bash
    register: status
    tags:
    - kind_start
  - debug:
      msg: "kind start status {{ status }}"