---

- name: lets manage terraform via ssh on somsi
  hosts: somsi
  connection: ssh
  gather_facts: false
  roles:
    - role: terraform/down
    - role: terraform/up

#- name: lets reboot all clients
  #hosts: m1
  ##hosts: m1,w1,w2
  #connection: ssh
  #gather_facts: false
  #roles:
    #- role: terraform/reboot
