---

- name: lets install woodpecker on ubuntu
  hosts: master
  connection: ssh
  gather_facts: true
  become: true

  tasks:
    - name: install woodpecker
      import_role:
        name: woodpecker/install
