---
# ansible-galaxy install -r requirements.yml

collections:

  - name: community.libvirt
    version: 1.3.0

  - name: community.general
    version: 9.3.0

  - name: community.postgresql
    version: 3.4.1

  - name: kubernetes.core
    version: 3.2.0

  - name: ansible.posix
    version: 1.3.0

# --- EOF
