---

- name: do hetzner stuff
  hosts: local
  connection: local

  tasks:

    - name: Ensure the server is stopped
      hetzner.hcloud.server:
        api_token: "{{ lookup('ansible.builtin.env', 'HETZNER_API_TOKEN') }}"
        name: rosso0815-master
        state: stopped
      register: out

    - name: debug out
      debug:
        msg: "out: {{ out }}"


# --- EOF
