---
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
    - name: private-reg-container
      image: registry.gitlab.com/rosso0815/rosso0815-gitlab-go:1.0.0.1
  # imagePullSecrets:
    # - name: credgitlab
