---

- name: create service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: traefik-dashboard
        namespace: kube-system
        labels:
          app.kubernetes.io/instance: traefik
          app.kubernetes.io/name: traefik-dashboard
      spec:
        type: ClusterIP
        ports:
          - name: traefik
            port: 9000
            targetPort: traefik
            protocol: TCP
        selector:
          app.kubernetes.io/instance: traefik-kube-system
          app.kubernetes.io/name: traefik

- name: create ingress
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Ingress
      metadata:
        name: traefik-ingress
        namespace: kube-system
        annotations:
          spec.ingressClassName: traefik
          cert-manager.io/cluster-issuer: my-own-issuer
          cert-manager.io/common-name: traefik.localnet
        labels:
          name: traefik
      spec:
        ingressClassName: traefik
        rules:
          - host: traefik.localnet
            http:
              paths:
                - backend:
                    service:
                      name: traefik-dashboard
                      port:
                        number: 9000
                  path: /
                  pathType: Prefix
        tls:
          - hosts:
              - traefik.localnet
            secretName: traefik-tls

# --- EOF
