###

GET http://127.0.0.1:8080/todos/ HTTP/1.1
content-type: application/json

###


GET http://127.0.0.1:8080/todos/1 HTTP/1.1
content-type: application/json

###

POST http://127.0.0.1:5000/todos/ HTTP/1.1
content-type: application/json

{
    "task": "sample"
}

###
