all:
    hosts:
        mail.example.com:
    children:
        webservers:
            hosts:
                localhost:
                    connection: local
                    http_port: 80
                    maxRequestsPerChild:
                    swpkg: undefined
                centos7:
                
        dbservers:
            hosts:
                one.example.com:
                two.example.com:
                three.example.com:
