---
- name: Test docker_inventory
  hosts: all
  connection: local
  gather_facts: true
  tasks:
    - name: Create a data container
      community.docker.docker_container:
        name: myubuntu
        image: ubuntu:14.04
        # volumes:
        #   - /data

    - name: Container present
      community.general.docker_container:
        name: myubuntu
        state: started
        image: ubuntu:14.04