---

- name: copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: check
  shell: |
    hostname
    ls -l "{{ systemd_dir }}/k3s-node.service"
  register: out

- name: debug check
  debug:
    msg: "out {{ out }}"

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: true
    state: restarted
    enabled: true
