---

- name: debug
  debug:
    msg: "@@@ start"

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: gitea-charts
    repo_url: https://dl.gitea.com/charts/
    force_update: true

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: '{{ gitea_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

# - name: create tls
#   environment:
#     KUBECONFIG: /etc/rancher/k3s/k3s.yaml
#   kubernetes.core.k8s:
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Secret
#       type: kubernetes.io/tls
#       metadata:
#         name: gitea-tls
#         namespace: '{{ gitea_namespace }}'
#       data:
#         tls.crt: '{{ gitea_tls_crt }}'
#         tls.key: '{{ gitea_tls_key }}'

- name: helm deploy gitea
  kubernetes.core.helm:
    name: gitea
    chart_ref: gitea-charts/gitea
    release_namespace: '{{ gitea_namespace }}'
    create_namespace: false
    update_repo_cache: true
    values:
      image:
        tag: 1.23.1
      actions:
        enabled: true
        provisioning:
          enabled: true
        # existingSecret: ""
        # existingSecretKey: ""
      redis-cluster:
        enabled: false
      postgresql:
        enabled: false
        global:
          postgresql:
            auth:
              password: gitea
              username: gitea
              database: database.localnet
      postgresql-ha:
        enabled: false
      persistence:
        enabled: true
        storageClass: local-path
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: my-own-issuer
          cert-manager.io/common-name: gitea.localnet
        hosts:
          - host: gitea.localnet
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - gitea.localnet
            secretName: gitea-tls
      gitea:
        config:
          server:
            PROTOCOL: http
            SSH_PORT: 22
            SSH_LISTEN_PORT: 2222
            DOMAIN: gitea.localnet
          database:
            DB_TYPE: postgres
            HOST: database.localnet:5432
            NAME: gitea
            USER: gitea
            PASSWD: gitea
            SCHEMA: gitea
          session:
            PROVIDER: memory
          cache:
            ADAPTER: memory
          queue:
            TYPE: level
          webhook:
            ALLOWED_HOST_LIST: '*'
            SKIP_TLS_VERIFY: true
          log:
            LEVEL: Debug
        admin:
          existingSecret: ""
          username: gitea_admin
          password: adminadmin
          email: "gitea@local.ch"
      # extraVolumes:
      #   - name: gitea-tls
      #     secret:
      #       secretName: gitea-tls
      # extraVolumeMounts:
      #   - name: gitea-tls
      #     readOnly: true
      #     mountPath: /certs

# --- EOF
