---

- name: debug
  debug:
    msg: "start"

- name: ufw is running
  ansible.builtin.systemd:
    state: started
    name: ufw

- name: Deny all access to port 6443
  community.general.ufw:
    rule: deny
    port: '6443'

- name: open fw
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: allow k3s for ip of own host
  community.general.ufw:
    rule: allow
    proto: tcp
    src: "{{ ansible_default_ipv4.address }}"
    port: "6443"
    comment: allow k3s

- name: Create etc rancher k3s dir
  ansible.builtin.file:
    path: /etc/rancher/k3s/
    state: directory
    mode: '0755'

- name: generate rancher resolv
  ansible.builtin.template:
    src: rancher_resolv_conf.j2
    dest: /etc/rancher/k3s/resolv.conf
    mode: '0644'

- name: generate rancher registry
  ansible.builtin.template:
    src: templates/k3s_server_registry.yaml
    dest: /etc/rancher/k3s/registries.yaml
    mode: '0644'

- name: install k3s
  shell: |
    set -aeEux
    K3S_TOKEN=12345
    K3S_RESOLV_CONF=/etc/rancher/k3s/resolv.conf
    INSTALL_K3S_VERSION={{ k3s_version }}
    INSTALL_K3S_EXEC="server"
    INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC --bind-address {{ k3s_bind_ip }}"
    INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC --write-kubeconfig-mode 644"
    INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC --selinux"
    INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC --tls-san master.localnet"
    INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC --resolv-conf /etc/rancher/k3s/resolv.conf"
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s-uninstall.sh

- name: copy remote k3s.yaml to local
  ansible.builtin.fetch:
    flat: true
    src: /etc/rancher/k3s/k3s.yaml
    dest: /var/tmp/k3s.yaml
    mode: '0400'

# --- EOF
