---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      run: echo
  replicas: 3
  template:
    metadata:
      labels:
        run: echo
    spec:
      containers:
        - name: echo
          image: rosso0815/goapp:1.0.1
          ports:
            - containerPort: 8080
