---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-ca
  namespace: sandbox
spec:
  isCA: true
  commonName: test-ca
  subject:
    organizations:
      - Rosso0815
    organizationalUnits:
      - HomeLab
  secretName: test-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
