# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: selfsigned
# spec:
#   selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami.localnet
  namespace: sandbox
spec:
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - whoami.localnet
  secretName: whoami.localnet
  issuerRef:
    name: selfsigned-issuer
    # kind: Issuer
