
SELECT "SEQUENCE", "PART_NUMBER", "PART_REVISION", "PART_VARIANT", "ACTION", "SOURCE_IP", "SOURCE_NAME", "READ_ONLY", "OVERNIGHT", "VPM_USER", "VPM_USER_EMAIL" 
    FROM "CDM"."MULTISITE_QUEUE"
GO


SELECT "$COID", "$COMPID", "$LOCKTYPE", "$COMPREF", "C_COMPNAME", "C_RESPONSIBLE", "C_ORG_RESPONSIBLE", "C_CREATE", "DURATION", "COMMENTS" 
    FROM "PRD11"."$LOCK" 
    where "$COID" = '4141641B35092C66'
GO

SELECT "$COID", "$COMPID", "S_TYPE_REP", "S_MNUMBER", "M_COMMENT", "M_REVIEWED", "M_REVIEWER", "M_APPROVED", "M_APPROVER", "M_SEQUENCE", "C_REVISION", "C_MATURITY", "D_TOOL", "D_PARM", "C_RESPONSIBLE", "C_ORG_RESPONSIBLE", "C_CREATE", "C_CREATE_USER", "C_LASTMOD", "C_LASTMOD_USER", "C_VERSION", "C_COMPID_DATA", "C_INTFORM", "C_COMPNAME_DATA", "C_SOFT_VER", "C_NICKNAME", "C_XMIN", "C_XMAX", "C_YMIN", "C_YMAX", "C_ZMIN", "C_ZMAX", "C_SIZE", "C_LAST_REPOSITORY", "P_CO_USER", "C_ORDER" 
    FROM "PRD11"."CATIA_MODEL" where c_nickname like '%300405%'
GO


SELECT "$COID", "$COMPID", "S_PIDENTNR", "S_VARIANT", "P_PROJECT", "P_PTYPE", "P_TITLE", "P_TYPE", "P_DESCRIPTION", "P_REVIEWED", "P_REVIEWER", "P_APPROVED", "P_APPROVER", "P_SEQUENCE", "C_PART_VERSION", "C_MATURITY", "D_TOOL", "D_PARM", "C_RESPONSIBLE", "C_ORG_RESPONSIBLE", "C_CREATE", "C_CREATE_USER", "C_LASTMOD", "C_LASTMOD_USER", "C_VERSION", "STATIC_PN", "S_LANG_REL", "P_RESP_DEP", "P_HTITLE", "P_STITLE", "P_RESP_DEP_N", "P_DERIVE", "C_SITE_RESPONSIBLE", "C_COUNT", "P_PDM_SYNCH_STATUS", "P_SYNCH_DEC", "C_OUT_OF_DATE", "S_CHECK_ID_FORMAT", "P_CO_USER", "P_MFG_STATUS", "C_ORDER" 
    FROM "PRD11"."PART_LIST"  where "$COID" = '4141641B35092C66'
GO


