---

apiVersion: v1
kind: Service
metadata:
  name: "{{DOCKER_APP}}"
spec:
  selector:
    app.kubernetes.io/name: "{{DOCKER_APP}}"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
