---

- name: Download k3s binary x64
  become: true
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
    timeout: 120

- name: Download k9s binary x64
  become: true
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.26.7/k9s_Linux_x86_64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
