---
- hosts: webservers
  
  tasks:

  - name: install ntpdate
    become: yes
    package:
      name: ntpdate
      state: present

  # - name: check if package installed
  #   command: rpm -q --qf "%{VERSION}\n" package
  #   args:
  #     warn: false
  #   register: package_installed
  #   failed_when: false
  #   changed_when: package_installed.rc != 0