
SELECT B3PROGRAMID FROM ADMM31A.B3PRGRM order by B3PROGRAMID asc
GO

SELECT usrgrpname FROM ADMM31A.ROLEASSN where USRGRPNAME like 'LP%R8%'
GO

SELECT PARTICIPANT FROM ADMM31A.USRGRP where PARTICIPANT like '%LP%'
GO
