---

- name: deploy gitea
  hosts: all
  gather_facts: true

  tasks:

    - name: Add stable chart repo
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      kubernetes.core.helm_repository:
        name: gitea-charts
        repo_url: https://dl.gitea.com/charts/
        force_update: true

    - name: Create a k8s namespace
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      kubernetes.core.k8s:
        name: '{{ gitea_namespace }}'
        api_version: v1
        kind: Namespace
        state: present

    - name: create tls
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/tls
          metadata:
            name: gitea-tls
            namespace: '{{ gitea_namespace }}'
          data:
            tls.crt: '{{ gitea_tls_crt }}'
            tls.key: '{{ gitea_tls_key }}'

    - name: helm deploy gitea
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      kubernetes.core.helm:
        name: gitea
        chart_ref: gitea-charts/gitea
        release_namespace: '{{ gitea_namespace }}'
        create_namespace: false
        update_repo_cache: true
        values:
          redis-cluster:
            enabled: false
          postgresql:
            enabled: false
            global:
              postgresql:
                auth:
                  password: gitea
                  username: gitea
                  database: database.localnet
          postgresql-ha:
            enabled: false
          persistence:
            enabled: false
          ingress:
            enabled: true
            className: traefik
            hosts:
              - host: gitea.localnet
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: gitea-tls
          gitea:
            config:
              server:
                PROTOCOL: http
                SSH_PORT: 22
                SSH_LISTEN_PORT: 2222
                DOMAIN: gitea.localnet
              database:
                DB_TYPE: postgres
                HOST: database.localnet:5432
                NAME: gitea
                USER: gitea
                PASSWD: gitea
                SCHEMA: gitea
              session:
                PROVIDER: memory
              cache:
                ADAPTER: memory
              queue:
                TYPE: level
              webhook:
                ALLOWED_HOST_LIST: '*'
            admin:
              existingSecret:
              username: gitea_admin
              password: adminadmin
              email: "gitea@local.ch"
          # extraVolumes:
          #   - name: gitea-tls
          #     secret:
          #       secretName: gitea-tls
          # extraVolumeMounts:
          #   - name: gitea-tls
          #     readOnly: true
          #     mountPath: /certs

# --- EOF