---

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: gitea-tls
  namespace: gitea
data:
  tls.crt: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNlVENDQWRxZ0F3SUJBZ0lSQWM5NmU0WkhnSjIydU43eWV2V2RJbEF3Q2dZSUtvWkl6ajBFQXdRd05qRUwKTUFrR0ExVUVCaE1DVlZNeENUQUhCZ05WQkFvVEFERUpNQWNHQTFVRUN4TUFNUkV3RHdZRFZRUURFd2huYVhSbApZUzFqWVRBZUZ3MHlOREEyTWpReE5ERTRNRFJhRncweU5qQTJNalF5TURFNE1EUmFNRHd4Q3pBSkJnTlZCQVlUCkFsVlRNUWt3QndZRFZRUUtFd0F4Q1RBSEJnTlZCQXNUQURFWE1CVUdBMVVFQXhNT1oybDBaV0V1Ykc5allXeHUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTSkRSdE1WTHEvWUlUMkJ6ZVZzeExudzdONQpSK3dIVGdVWlhRYWRtZVdqb1VMMHdNSWRzSXBnSGVDS093dXhnQ1ZFT1d5alpWZE5PcWIza2xObGlIREhvNEhDCk1JRy9NQTRHQTFVZER3RUIvd1FFQXdJRHFEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUIKQWY4RUFqQUFNQ2tHQTFVZERnUWlCQ0N4MlF2OGpIbERuMjdEM2VnQjZZaW9GSFQra3V3a3hRT0JRSGlHUkNUNwphakFyQmdOVkhTTUVKREFpZ0NCRXRtRlVyaEdkTmxZYjl1cWl3N0laSmZjb2h2R25tZUJBdWdOYlZldzhaREFmCkJnTlZIUkVFR0RBV2dnNW5hWFJsWVM1c2IyTmhiRzVsZEljRXdLaXlGVEFSQmdsZ2hrZ0JodmhDQVFFRUJBTUMKQmtBd0NnWUlLb1pJemowRUF3UURnWXdBTUlHSUFrSUFySW9TT05sTkpwWGFWd3JPNGNVMHd1RnN6akJwVjhoaApJKzFEZzFkZ1U5SWJHTTNlRWNRaFF3MVJ1YjFnQ2g0YWpTMHlWYzVaV0N1cW1lZEtraHZXNWFJQ1FnRy82SnZFCmVoOU85UDk4MFBXUGdGbWlINEozUEgrZk1rdXVzL2xlOCt1TGRRbFgrTkQ3TE9XTlpWMmFiZ0hhZWxCTEQwMFEKOTJLV0ZHdll0azFFOGNsOVFnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='

  tls.key: 'LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5RVFFmek85SnZuR0R0dUZYZVVrVUNQUlRhakNyRERYYzgwOEtUYzgrVnpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFaVEwYlRGUzZ2MkNFOWdjM2xiTVM1OE96ZVVmc0IwNEZHVjBHblpubG82RkM5TURDSGJDSwpZQjNnaWpzTHNZQWxSRGxzbzJWWFRUcW05NUpUWllod3h3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo='

# --- EOF
