---

- name: debug
  debug:
    msg:
      - "DOCKER_REPO_USERNAME: {{ DOCKER_REPO_USERNAME }}"
      - "DOCKER_REPO_EMAIL: {{ DOCKER_REPO_EMAIL }}"
      - "DOCKER_REPO_SECRET: {{ DOCKER_REPO_SECRET }}"

- name: fix /var/tmp/k3s.yaml
  command: chmod go-rwx /var/tmp/k3s.yaml

- name: delete namespace cert-manager
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: absent
    wait: true

- name: Add a repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    force_update: true

- name: helm deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: v1.15.3
    create_namespace: true
    release_namespace: cert-manager
    update_repo_cache: true
    set_values:
      - value: crds.enabled=true
  register: out

- name: debug
  debug:
    var: out

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ gitea_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: create own ca
  kubernetes.core.k8s:
    state: present
    name: my-own-ca
    namespace: cert-manager
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: my-own-ca
        namespace: cert-manager
      data:
        tls.crt: "{{ lookup('file', 'ca.crt') | b64encode }}"
        tls.key: "{{ lookup('file', 'ca.key') | b64encode }}"

- name: create own issuer
  kubernetes.core.k8s:
    state: present
    name: my-own-ca
    namespace: cert-manager
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: my-own-issuer
      spec:
        ca:
          secretName: my-own-ca

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ gitea_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: cowboysysop
    repo_url: https://cowboysysop.github.io/charts/
    force_update: true

- name: helm deploy whoami
  kubernetes.core.helm:
    name: whoami
    chart_ref: cowboysysop/whoami
    release_namespace: "{{ gitea_namespace }}"
    update_repo_cache: true
    values:
      replicaCount: 1
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: my-own-issuer
          cert-manager.io/common-name: whoami.localnet
        hosts:
          - host: whoami.localnet
            paths:
              - /
        tls:
          - hosts:
              - whoami.localnet
            secretName: whoami-tls

# --- EOF
