---

- name: do web stuff
  hosts: web
  connection: ssh

  tasks:
    - name: test web
      debug:
        msg: test {{ test }}

- name: db stuff
  hosts: db
  connection: ssh
  gather_facts: true
  tasks:
    - name: test db
      debug:
        msg: test {{ test }}
